extends:
  - "plugin:@typescript-eslint/recommended"
  - prettier
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
  - react
  - react-hooks
  - unused-imports
root: true
rules:
  "@next/next/no-img-element": 0
  prettier/prettier: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: "^_"
      args: after-used
      argsIgnorePattern: "^_"
