bracketSpacing: true
importOrder:
  - "^(react/(.*)$)|^(react$)"
  - "^(next/(.*)$)|^(next$)"
  - "<THIRD_PARTY_MODULES>"
  - ""
  - "^types$"
  - "^@/env(.*)$"
  - "^@/types/(.*)$"
  - "^@/config/(.*)$"
  - "^@/lib/(.*)$"
  - "^@/hooks/(.*)$"
  - "^@/components/ui/(.*)$"
  - "^@/components/(.*)$"
  - "^@/styles/(.*)$"
  - "^@/app/(.*)$"
  - ""
  - "^[./]"
jsxSingleQuote: true
semi: false
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false

plugins:
  - "@ianvs/prettier-plugin-sort-imports"
